# Development environment for PatentsView-Evaluation

name: er-evaluation

dependencies:
  - python=3.10
  - pip>=22
  - ipython
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - scipy
  - black
  - pip:
    - igraph
    - plotly
    - sphinx-autoapi
    - Sphinx
    - myst_parser
    - pydata-sphinx-theme
    - m2r2
    - sphinx-lesson
    - sphinx-design
    - parse