name: Python package

on: [push, pull_request]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install and load
      run: |
        pip install .
        python -c "import er_evaluation"

    - name: Test with pytest
      run: |
        pip install pytest testbook ipykernel jupyter pyhamcrest
        pytest --doctest-modules
        pytest .
